language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: tsSBsYzYaCXQmkEMJXsbJmMIVIlAJC8eVe/JCYt9R/0qSqJfB/B17ftAOqhgqRF+0ZuiiMjWbrDMiB3ueUhwy9VHlMvMhcYMv/AadxPCIxTfbQogi0K5ICW2x+kQbz/G/3LmJZBWIr6PUYscPcdA47T8KCZo+JeQsqFmJNOfnnQXGROWG8sGDj3+fj1kHZ2fhqiU6rGOswJCMXE7hmYjzQ/WWpO6qHxAj0oiqqE3mAfD9RG6j0xG3/qvZvA/NNlXL//TkHkZRbRLDJTDxf8DHyMYJPEohJDwFSGgnvdTYQH6MS3/zTu226azPxNR1QU9UendUa3F7glvLpLBhKXVRCrKvqO0dNC2Vl8b6SVrhtug7AthlRHael+qyu5R8/wu5kbK8bWPfiSlDhyyLMNE+Qb+NjXTGXrkYEEuIpD4Gi4NvnLVS/4IaA2STnXiLIiabfHEEzcYdWuYzIPCB9q/cfA27sJqnf8zQKqrwWtFM8ZCZ568jYQkBHkhilFOng8POPs/MFscNnWEhuPuU1ytM4MIZRgPsK5alj2pvRR+GfWQSj4oAvsfoZBNgKkMwSwZEaqaip+q180rhGrjDZU76P9b+r7o8BgC+DSFi3/BY0ZRFNWgSxohc5xYEiHaEjCF4jR4SuTFObWWmZZEh43t8KhA1qBLBwtqDUzaXqnmkyI=
  app: shelf-app
  on:
    repo: Quanda/Shelf
