language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: y6mNfcsdPkJskhgFY8UeOgF6JiljusSYeDsDOWMSPt3N7cBjoNWE+LUOXQMpKTDWAi8Jn+Ke30HtJCTRsyAY3aPcSIxdRiOO9BjDmVZWiSaTuUHRVvajfr8pPTk6THNxsE3UtkjjzzIDY5tNLq6OU9DLDwJURammdm2RbXbQYg7DURBU/vYiIv+JAdOSWraSC9/IOJ5B5bT4bm3S+17scw5HOl6OiLg4fYumR/hTMLrcYuoWo9k4rMcxb85UBC5UrLpQCPfp9osPH+YU+sOV+TcxvkJ3Sd5oYwejH84Jya/fm8O8Vtv4q2qvb/IhjZbLrEhJHmx4ZeG2QeVC7WUiR73c4yz+kf+B/zwIZE6+75sjmKddtaP+DNoK0kxYhP6gRWV7hYDRpnC16r++DxN9Ji5niHdMA09KsX/orFgZO/nWA9qP4NxlsEDQJkG5NcbQeTLit9RgELSOJfZGwfsYy+SZkyj+yuqG9OnYHrc2INQ/v0/hjq2H+L/sE3PVhDPvlv/mocu0jvIzvJx9XB3VZzpPrHflky4ZjfsQwNDn4sLumpe1nr3yEYuOxJm+RvwXXzys74rr5JkqW++z3dr8PgR/nZnZy6qf2DgUwckgdj475cn2pVy02cXf6I0PKP26VjlVdaoZq+8Z80/Gsj+yBWzSEOlkuXIBMu3XkDp23qw=
  app: shelf-app
  on:
    repo: Quanda/Shelf
